swagger: "2.0"
info:
  description: "This is a sample Swagger file for defining our API interface."
  version: "1.0.0"
  title: "Scrooge McBot"
host: "scrooge.mcbot.io"
basePath: "/"
tags:
- name: "tag1"
  description: "Some information about your first tag"
- name: "tag2"
  description: "Some other information about your second tag"
- name: "dialogflow"
  description: "The endpoint to deal with dialogflow JSON"
schemes:
- "https"
paths:
  /df:
    post:
      tags:
      - "dialogflow"
      summary: "Process information from DialogFlow"
      description: "Parses and responds to JSON posted from dialogflow"
      operationId: "dialogflow"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "JSON structure from dialogflow"
        required: true
        schema:
          type: "object"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/DialogflowResponse'
        "405":
          description: "Invalid input"
definitions:
  DialogflowResponse:
    type: "object"
    required:
    - "displayText"
    properties:
      displayText:
        type: "string"
      speech:
        type: "string"
